/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.education.transferobj;

import java.io.Serializable;

/** 
 * This class represents the primary key of the t_affiliate table.
 */
public class TAffiliatePk implements Serializable
{
	protected String affiliateId;

	/** 
	 * Sets the value of affiliateId
	 */
	public void setAffiliateId(String affiliateId)
	{
		this.affiliateId = affiliateId;
	}

	/** 
	 * Gets the value of affiliateId
	 */
	public String getAffiliateId()
	{
		return affiliateId;
	}

	/**
	 * Method 'TAffiliatePk'
	 * 
	 */
	public TAffiliatePk()
	{
	}

	/**
	 * Method 'TAffiliatePk'
	 * 
	 * @param affiliateId
	 */
	public TAffiliatePk(final String affiliateId)
	{
		this.affiliateId = affiliateId;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof TAffiliatePk)) {
			return false;
		}
		
		final TAffiliatePk _cast = (TAffiliatePk) _other;
		if (affiliateId == null ? _cast.affiliateId != affiliateId : !affiliateId.equals( _cast.affiliateId )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (affiliateId != null) {
			_hashCode = 29 * _hashCode + affiliateId.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mycompany.myapp.dto.TAffiliatePk: " );
		ret.append( "affiliateId=" + affiliateId );
		return ret.toString();
	}

}
